
//Auth actions
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const VERIFICATION_SUCCESS = 'VERIFICATION_SUCCESS';
export const USER_CONFIRMED_VERIFICATION = 'USER_CONFIRMED_VERIFICATION';
export const USER_DISMISSED_VERIFICATION_WARNING ='USER_DISMISSED_VERIFICATION_WARNING';

//Error actions
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

//Post actions
export const UPDATE_POST_DATA = 'UPDATE_POST_DATA';
export const NEW_POST_SUCCESS = 'NEW_POST_SUCCESS';
export const NEW_POST_FAIL = 'NEW_POST_FAIL';

//Comment actions
export const NEW_COMMENT_SUCCESS = 'NEW_COMMENT_SUCCESS'
export const NEW_COMMENT_FAIL = 'NEW_COMMENT_FAIL'